/**
 * @file
 * Vite config for the React SPA: builds `gui/src` to `dist/` (deployed to
 * Netlify). Allows the dev server to read the repo-root `src/` engine above the
 * gui root, and pins `lodash` to the SPA's own copy so the build is self-contained
 * (Vite 8 / Rolldown treats an unresolved import as a hard error).
 */
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import path from "node:path";
import { apiPlugin } from "./vite-plugin-api.js";

const require = createRequire(import.meta.url);

// The SPA imports the shared prompt engine from repo-root core/ (which bundles
// the dynamic-prompts/ lists/ expansions/ data via import.meta.glob). Allow the
// dev server to read those files above the gui root.
const repoRoot = fileURLToPath(new URL("..", import.meta.url));

// Those repo-root src/ files (the core engine, every dynamic prompt, and
// promptFilesAndSuggestions.js) `import _ from "lodash"`. Because they live
// outside gui/, resolution from them would not find gui's own lodash —
// and Vite 8 / Rolldown treats an unresolved import as a hard error (Vite 6 /
// Rollup only warned). Pin lodash to the SPA's installed copy so the build is
// self-contained: it works on CI and on Netlify, neither of which installs the
// repo-root node_modules.
const lodashDir = path.dirname(require.resolve("lodash/package.json"));

// react-intl message IDs are auto-generated by babel-plugin-formatjs from each
// message's defaultMessage + description. The pattern MUST match the one the
// FormatJS CLI uses in the `i18n:extract` script (see package.json), so the IDs
// the bundle emits line up with the IDs in the extracted/compiled catalogs.
const formatjsBabelPlugin = [
  "formatjs",
  {
    idInterpolationPattern: "[sha512:contenthash:base64:6]",
    // Keep the inline defaultMessage in the bundle so the source locale (en)
    // renders with no catalog, and any locale missing a key falls back to it.
    removeDefaultMessage: false,
  },
];

// Plain Vite + React SPA. Builds to dist/ as static files (deployed to Netlify).
export default defineConfig({
  // react() for the SPA; apiPlugin() serves /api/* during local dev (hosted-generation
  // proxy + local-file storage) — the local equivalent of the Netlify function.
  plugins: [react({ babel: { plugins: [formatjsBabelPlugin] } }), apiPlugin()],
  resolve: {
    alias: { lodash: lodashDir },
    dedupe: ["lodash"],
  },
  server: {
    port: 5173,
    fs: { allow: [repoRoot] },
  },
  build: {
    // Keep the code-split prompt corpus OFF the entry's <link rel="modulepreload"> list. The engine
    // fetches it at runtime via an explicit import() after first paint (promptEngine.ensureCatalog);
    // a modulepreload would drag its ~430 KB back onto the initial download and re-block LCP. The
    // runtime import() still fetches the chunk when it's actually needed — it just isn't preloaded.
    modulePreload: {
      resolveDependencies: (_filename, deps) =>
        deps.filter((dep) => !/(?:prompt-data|browserCatalogData)-/.test(dep)),
    },
    rollupOptions: {
      output: {
        // Split the monolith into focused, independently-cacheable chunks (Vite 8 / Rolldown
        // `advancedChunks`). Vendors change rarely, so isolating them means an app-code change
        // doesn't re-download React/lodash. The eagerly-globbed prompt data (the largest single
        // contributor) becomes its own chunk too — still fetched for the Generate view, but in
        // parallel and cached apart from the engine/app code. CodeMirror is intentionally NOT
        // grouped here: it already lives in the lazy `Manage` chunk and must stay on-demand.
        advancedChunks: {
          groups: [
            { name: "react", test: /[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/ },
            {
              name: "intl",
              test: /[\\/]node_modules[\\/](react-intl|@formatjs|intl-messageformat)/,
            },
            { name: "lodash", test: /[\\/]node_modules[\\/]lodash[\\/]/ },
            { name: "prompt-data", test: /[\\/]data[\\/](dynamic-prompts|lists|presets)[\\/]/ },
          ],
        },
      },
    },
  },
});
