/**
 * Generate gui/src/styles/foundation/accents.css from the accent presets
 * (gui/src/theme/presets.js — the single source of truth). Re-run whenever the
 * presets change:  node scripts/gen-accents.mjs
 *
 * Each accent remaps --accent + --accent-ink; --accent-strong (button hover) and
 * --accent-soft (tints) derive from --accent in CSS, so they're set once here.
 * The default accent is the bare :root in foundation/tokens.css, so it's skipped.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { ACCENTS, DEFAULT_ACCENT } from "../gui/src/theme/presets.js";

const STRONG = "color-mix(in oklab, var(--accent), #000 12%)";

let out =
  `/* GENERATED by scripts/gen-accents.mjs from gui/src/theme/presets.js — do not edit by hand.\n` +
  ` *\n` +
  ` * Accent presets: each remaps --accent + --accent-ink. --accent-strong (button\n` +
  ` * hover) and --accent-soft (tints) derive from --accent, so they're set once.\n` +
  ` * The default accent (${DEFAULT_ACCENT}) is the :root default in foundation/tokens.css and is\n` +
  ` * intentionally not repeated here. Bright neon on dark, soft pastel on light.\n` +
  ` * Lives in @layer tokens (imported right after tokens.css). Regenerate with\n` +
  ` * node scripts/gen-accents.mjs\n` +
  ` */\n\n`;

for (const a of ACCENTS) {
  if (a.id === DEFAULT_ACCENT) continue;
  out +=
    `:root[data-accent="${a.id}"] {\n` +
    `  --accent: ${a.dark.accent};\n` +
    `  --accent-ink: ${a.dark.ink};\n` +
    `  --accent-strong: ${STRONG};\n` +
    `}\n\n` +
    `:root[data-theme="light"][data-accent="${a.id}"] {\n` +
    `  --accent: ${a.light.accent};\n` +
    `  --accent-ink: ${a.light.ink};\n` +
    `}\n\n`;
}

const dest = path.resolve(import.meta.dirname, "../gui/src/styles/foundation/accents.css");
writeFileSync(dest, out);
console.log(`wrote ${dest} (${ACCENTS.length - 1} accents)`);
