/**
 * Generate targets/web/frontend/styles/foundation/accents.css from the system theme files
 * (targets/web/frontend/theme/themes/*.json — each file is one theme). Re-run whenever the
 * theme files change:  node scripts/gen-accents.mjs  (or: npm run gen:accents)
 *
 * Each theme remaps --accent + --accent-ink; --accent-strong (button hover) and
 * --accent-soft (tints) derive from --accent in CSS, so they're set once here.
 * The default theme is the bare :root in foundation/tokens.css, so it's skipped.
 *
 * Node-side loader: reads the folder with fs (the app + tests use the Vite glob
 * in targets/web/frontend/theme/presets.js — same files, two isomorphic loaders).
 */
import { writeFileSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";

const DEFAULT_ACCENT = "mint";
const STRONG = "color-mix(in oklab, var(--accent), #000 12%)";

const themesDir = path.resolve(import.meta.dirname, "../targets/web/frontend/theme/themes");
const accents = readdirSync(themesDir)
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => JSON.parse(readFileSync(path.join(themesDir, f), "utf8")));

let out =
  `/* GENERATED by scripts/gen-accents.mjs from targets/web/frontend/theme/themes/*.json — do not edit by hand.\n` +
  ` *\n` +
  ` * Accent presets: each remaps --accent + --accent-ink. --accent-strong (button\n` +
  ` * hover) and --accent-soft (tints) derive from --accent, so they're set once.\n` +
  ` * The default theme (${DEFAULT_ACCENT}) is the :root default in foundation/tokens.css and is\n` +
  ` * intentionally not repeated here. Bright neon on dark, soft pastel on light.\n` +
  ` * Lives in @layer tokens (imported right after tokens.css). Regenerate with\n` +
  ` * node scripts/gen-accents.mjs\n` +
  ` */\n\n`;

for (const a of accents) {
  if (a.id === DEFAULT_ACCENT) continue;
  out +=
    `:root[data-accent="${a.id}"] {\n` +
    `  --accent: ${a.dark.accent};\n` +
    `  --accent-ink: ${a.dark.ink};\n` +
    `  --accent-strong: ${STRONG};\n` +
    `}\n\n` +
    `:root[data-theme="light"][data-accent="${a.id}"] {\n` +
    `  --accent: ${a.light.accent};\n` +
    `  --accent-ink: ${a.light.ink};\n` +
    `}\n\n`;
}

const dest = path.resolve(import.meta.dirname, "../targets/web/frontend/styles/foundation/accents.css");
writeFileSync(dest, out);
console.log(`wrote ${dest} (${accents.length - 1} accents)`);
